apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bgghelmchart.fullname" . }}
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bgghelmchart.fullname" . }}
      app.kubernetes.io/version: "v1"
  # The following can be defined in another fill
  # Deployment will match by the labels define in the Pod yaml config
  template:
    metadata:
      name: {{ include "bgghelmchart.fullname" . }}
      # kubernetes works with label, anything with the label will receieve the request
      labels:
        app.kubernetes.io/name: {{ include "bgghelmchart.fullname" . }}
        app.kubernetes.io/version: "v1"
        owner: yaofeng
    spec:
      containers:
      - name: {{ include "bgghelmchart.fullname" . }}
        # image: stackupiss/bgg-app:v1
        image: stackupiss/bgg-app:v1
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "changeit"
          - name: MYSQL_DATABASE
            value: "bgg"
          - name: APP_PORT
            value: "3000"
          - name: APP_DIR
            value: "/app"
          - name: BGG_DB_HOST
            value: "bgg-db-svc.workshop02-bgg-db-ns.svc.cluster.local"
          - name: BGG_DB_PORT
            value: "3306"
          - name: BGG_DB_USER
            value: "root"
          - name: BGG_DB_PASSWORD
            value: "changeit"
        # These are the port which the "container" will be exposing
        ports:
          - name: {{ include "bgghelmchart.fullname" . }}
            containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 16m