apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bggappv1hpa
  namespace: workshop02-bgg-db-ns
spec:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 2
  scaleTargetRef:
    kind: Deployment
    name: bgg-app-deployment-v1
    apiVersion: apps/v1
