apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdbpvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "dobs.csi.digitalocean.com"
  namespace: workshop02-bgg-db-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage